name: Windows - Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Download and install essentials
        run: |
          curl.exe -L -o Downloads.bat "https://raw.githubusercontent.com/ELMOUMINEMOHSSINE/litemanager-tool/main/Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to Litemanager
        run: |
          curl.exe -L -o show.bat "https://raw.githubusercontent.com/ELMOUMINEMOHSSINE/litemanager-tool/main/show.bat"
          cmd /c show.bat

      - name: Time Counter
        run: |
          curl.exe -L -o loop.bat "https://raw.githubusercontent.com/ELMOUMINEMOHSSINE/litemanager-tool/main/loop.bat"
          cmd /c loop.bat
